package com.yahoo.hakunamatata.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.yahoo.hakunamatata.dao.Post;
import com.yahoo.hakunamatata.dao.User;
import com.yahoo.hakunamatata.dao.Like;
import com.yahoo.hakunamatata.dao.Picture;

import com.yahoo.hakunamatata.dao.PostDao;
import com.yahoo.hakunamatata.dao.UserDao;
import com.yahoo.hakunamatata.dao.LikeDao;
import com.yahoo.hakunamatata.dao.PictureDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig postDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig likeDaoConfig;
    private final DaoConfig pictureDaoConfig;

    private final PostDao postDao;
    private final UserDao userDao;
    private final LikeDao likeDao;
    private final PictureDao pictureDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        postDaoConfig = daoConfigMap.get(PostDao.class).clone();
        postDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        likeDaoConfig = daoConfigMap.get(LikeDao.class).clone();
        likeDaoConfig.initIdentityScope(type);

        pictureDaoConfig = daoConfigMap.get(PictureDao.class).clone();
        pictureDaoConfig.initIdentityScope(type);

        postDao = new PostDao(postDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        likeDao = new LikeDao(likeDaoConfig, this);
        pictureDao = new PictureDao(pictureDaoConfig, this);

        registerDao(Post.class, postDao);
        registerDao(User.class, userDao);
        registerDao(Like.class, likeDao);
        registerDao(Picture.class, pictureDao);
    }
    
    public void clear() {
        postDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
        likeDaoConfig.getIdentityScope().clear();
        pictureDaoConfig.getIdentityScope().clear();
    }

    public PostDao getPostDao() {
        return postDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public LikeDao getLikeDao() {
        return likeDao;
    }

    public PictureDao getPictureDao() {
        return pictureDao;
    }

}
