package com.yahoo.hakunamatata.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LIKE.
 */
public class Like {

    private Long internalId;
    private String id;
    private Integer total_count;

    public Like() {
    }

    public Like(Long internalId) {
        this.internalId = internalId;
    }

    public Like(Long internalId, String id, Integer total_count) {
        this.internalId = internalId;
        this.id = id;
        this.total_count = total_count;
    }

    public Long getInternalId() {
        return internalId;
    }

    public void setInternalId(Long internalId) {
        this.internalId = internalId;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Integer getTotal_count() {
        return total_count;
    }

    public void setTotal_count(Integer total_count) {
        this.total_count = total_count;
    }

}
